apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consumer01

# Referencias a los kustomizations separados
resources:
  - json-config
  - patches/patch-catalogue-ui.yaml
  - patches/patch-simpl-fe-participant.yaml
  - patches/patch-simpl-fe-usersroles.yaml
