apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authority01
generatorOptions:
  disableNameSuffixHash: true

# ConfigMap para logos
configMapGenerator:
  - name: simpl-logo
    files:
      - simpl-logo.svg=logos/simpl-logo.svg
