apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authority01

# Referencias a los kustomizations separados
resources:
  - json-kustomization.yaml
  - logos-kustomization.yaml
  - patches/patch-simpl-fe-onboarding.yaml
  - patches/patch-simpl-fe-participant.yaml
  - patches/patch-simpl-fe-sap.yaml
  - patches/patch-simpl-fe-usersroles.yaml
