apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authority01
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authority-onboarding-html
    files:
      - index.html=html/onboarding/index.html
      - onboarding/index.html=html/onboarding/index.html
      - simpl-shell/index.html=html/simpl-shell/index.html
      - sap/index.html=html/sap/index.html
      - identity-provider/index.html=html/identity-provider/index.html
      - usersandroles/index.html=html/usersandroles/index.html
      - participant-utility/index.html=html/participant-utility/index.html
  - name: authority-participant-html
    files:
      - index.html=html/participant/index.html
      - onboarding/index.html=html/participant/onboarding/index.html
      - simpl-shell/index.html=html/participant/simpl-shell/index.html
      - sap/index.html=html/participant/sap/index.html
      - identity-provider/index.html=html/participant/identity-provider/index.html
      - usersandroles/index.html=html/participant/usersandroles/index.html
      - participant-utility/index.html=html/participant/participant-utility/index.html
  - name: authority-sap-html
    files:
      - index.html=html/sap/index.html
      - onboarding/index.html=html/sap/onboarding/index.html
      - simpl-shell/index.html=html/sap/simpl-shell/index.html
      - sap/index.html=html/sap/sap/index.html
      - identity-provider/index.html=html/sap/identity-provider/index.html
      - usersandroles/index.html=html/sap/usersandroles/index.html
      - participant-utility/index.html=html/sap/participant-utility/index.html
  - name: authority-usersroles-html
    files:
      - index.html=html/usersroles/index.html
      - onboarding/index.html=html/usersroles/onboarding/index.html
      - simpl-shell/index.html=html/usersroles/simpl-shell/index.html
      - sap/index.html=html/usersroles/sap/index.html
      - identity-provider/index.html=html/usersroles/identity-provider/index.html
      - usersandroles/index.html=html/usersroles/usersandroles/index.html
      - participant-utility/index.html=html/usersroles/participant-utility/index.html
